"""initial schema - drishti foundation

Revision ID: 67e490029aa1
Revises: 
Create Date: 2026-09-23 01:13:33.972854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '67e490029aa1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_label', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('quality_status', sa.String(length=50), nullable=False),
    sa.Column('quality_summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('officer',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('district', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('peer_group',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('district', sa.String(length=255), nullable=True),
    sa.Column('sector', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('financial_year', sa.String(length=20), nullable=True),
    sa.Column('size_band', sa.String(length=50), nullable=True),
    sa.Column('definition', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_definition',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rule_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('source_reference', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_code')
    )
    op.create_table('detection_run',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('ruleset_version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('work_id', sa.String(length=64), nullable=False),
    sa.Column('mp_name', sa.String(length=255), nullable=True),
    sa.Column('constituency', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('district', sa.String(length=255), nullable=False),
    sa.Column('location_text', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('sector', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sanctioned_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('expenditure', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('financial_progress', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('physical_progress', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('sanction_date', sa.Date(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('implementing_agency', sa.String(length=255), nullable=True),
    sa.Column('contractor_name', sa.String(length=255), nullable=True),
    sa.Column('expected_duration_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_projects_category', 'projects', ['category'], unique=False)
    op.create_index('ix_projects_latlng', 'projects', ['latitude', 'longitude'], unique=False)
    op.create_index('ix_projects_state_district', 'projects', ['state', 'district'], unique=False)
    op.create_index('ix_projects_status', 'projects', ['status'], unique=False)
    op.create_index('ix_projects_work_dataset', 'projects', ['work_id', 'dataset_id'], unique=False)
    op.create_table('investigation_case',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_number', sa.String(length=50), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('assigned_officer_id', sa.String(length=36), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_type', sa.String(length=40), nullable=True),
    sa.Column('resolution_summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_officer_id'], ['officer.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_number')
    )
    op.create_index('ix_case_officer', 'investigation_case', ['assigned_officer_id'], unique=False)
    op.create_index('ix_case_status_priority', 'investigation_case', ['status', 'priority'], unique=False)
    op.create_table('project_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('cost_deviation_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('peer_median_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('peer_p75_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('peer_percentile', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('financial_physical_gap', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('expenditure_ratio', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('elapsed_days', sa.Integer(), nullable=True),
    sa.Column('expected_duration_days', sa.Integer(), nullable=True),
    sa.Column('delay_days', sa.Integer(), nullable=True),
    sa.Column('agency_share_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('ml_anomaly_score', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('duplicate_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.Column('calculation_version', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('project_peer',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('peer_group_id', sa.String(length=36), nullable=False),
    sa.Column('peer_count', sa.Integer(), nullable=False),
    sa.Column('median_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('p75_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('percentile', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['peer_group_id'], ['peer_group.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_signal',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('signal_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('triggered', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('observed_value', sa.JSON(), nullable=True),
    sa.Column('reference_value', sa.JSON(), nullable=True),
    sa.Column('difference_value', sa.JSON(), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_signal_project_severity', 'project_signal', ['project_id', 'severity'], unique=False)
    op.create_index('ix_signal_type', 'project_signal', ['signal_type'], unique=False)
    op.create_table('related_project',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('related_project_id', sa.String(length=36), nullable=False),
    sa.Column('text_similarity', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('location_distance_m', sa.Numeric(precision=12, scale=1), nullable=True),
    sa.Column('cost_similarity', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('category_match', sa.Boolean(), nullable=True),
    sa.Column('time_overlap', sa.Boolean(), nullable=True),
    sa.Column('combined_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['related_project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_related_score', 'related_project', ['project_id', 'combined_score'], unique=False)
    op.create_table('case_event',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['officer.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['investigation_case.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('signal_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('file_reference', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['investigation_case.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['project_signal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_note',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['officer.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['investigation_case.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('report_number', sa.String(length=50), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('file_reference', sa.String(length=500), nullable=False),
    sa.Column('generated_by', sa.String(length=36), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('report_version', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['investigation_case.id'], ),
    sa.ForeignKeyConstraint(['generated_by'], ['officer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_number')
    )
    op.create_table('signal_evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('signal_id', sa.String(length=36), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('field_value', sa.Text(), nullable=False),
    sa.Column('reference_label', sa.String(length=255), nullable=True),
    sa.Column('reference_value', sa.Text(), nullable=True),
    sa.Column('calculation', sa.Text(), nullable=True),
    sa.Column('provenance', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['project_signal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signal_evidence')
    op.drop_table('report')
    op.drop_table('case_note')
    op.drop_table('case_evidence')
    op.drop_table('case_event')
    op.drop_index('ix_related_score', table_name='related_project')
    op.drop_table('related_project')
    op.drop_index('ix_signal_type', table_name='project_signal')
    op.drop_index('ix_signal_project_severity', table_name='project_signal')
    op.drop_table('project_signal')
    op.drop_table('project_peer')
    op.drop_table('project_metrics')
    op.drop_index('ix_case_status_priority', table_name='investigation_case')
    op.drop_index('ix_case_officer', table_name='investigation_case')
    op.drop_table('investigation_case')
    op.drop_index('ix_projects_work_dataset', table_name='projects')
    op.drop_index('ix_projects_status', table_name='projects')
    op.drop_index('ix_projects_state_district', table_name='projects')
    op.drop_index('ix_projects_latlng', table_name='projects')
    op.drop_index('ix_projects_category', table_name='projects')
    op.drop_table('projects')
    op.drop_table('detection_run')
    op.drop_table('rule_definition')
    op.drop_table('peer_group')
    op.drop_table('officer')
    op.drop_table('datasets')
    # ### end Alembic commands ###
